# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
author: Pierre Louchet
title: les 24 heures du manche
email: les24hdumanche@gmail.com
description: > # this means to ignore newlines until "keywords:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keywords:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://les24heuresdumanche.com" # the base hostname & protocol for your site
twitter_username:
github_username:  les24heuresdumanche
facebook_page: https://www.facebook.com/24h.du.manche/
youtube_page: https://www.youtube.com/channel/UCNIQWbrVILyGUIfGV94c1_w
soundcloud_page: https://soundcloud.com/les24hdumanche

# Build settings
markdown: kramdown
